### PR TITLE
YOURLS version 1.8.1 functionality

### PR DESCRIPTION
**Pull request by mattv8**
Updated so yourls-ldap-plugin now functions with latest YOURLS version (1.8.1 as of May 24, 2021).
- LDAPAUTH_ADD_NEW' flag working again with latest YOURLS config, so users can be cached in the config.

### CODE REVIEW

**Comment by k3a** [comment]
Thanks for the contribution! Are you sure it will be backward-compatible with older YOURLS? Especially renaming is_valid_user to shunt_is_valid_user. I don't use YOURLS actively anymore so it would be difficult for me to properly test.

**Comment by mattv8** [comment]
Hi k3a, apologies for the delayed response. I can't speak for certain that this is backward-compatible. Would it be ideal to just branch my PR? In my opinion, branching would be the path of least resistance. If backwards compatibility is important enough to you, I can dig deeper and run some tests with older versions, however this will take time.

We might be able to get backwards compatibility with some version-logic. Something like `if (version < 1.8.1) use is_valid_user; else shunt_is_valid_user` might do the trick.

From my personal testing of is_valid... to shunt_is_valid... I could not get `is_valid_user` to properly function with the latest version of YourLS and documentation on API filters is sparse. I'm not overly familiar with YourLS API, so it could just be due to a limitation of my understanding of the API.  Am I missing some better documentation somewhere?

Let me know what you think the best course of action is.

**Comment by IMIjrebassa** [comment]
Hello, I'have installed yourls 1.9.2 and your ldap plugin, I'have modified the ldap plugin because I could not search in ldap, now I can bind to ldap and search in ldap, but now appears a new error when I login with a new user : Couldn't add user, plugin may not be compatible with YourLS version. When you will upload a new ldap plugin version compatible with Yourls last version. Thanks.

**Comment by IMIjrebassa** [comment]
Hello, I'have could login in Yourls with ldap user setting LDAPAUTH_NEW_USER to false and LDAPAUTH_ALL_USERS_ADMIN to true. Now my doubt is: only can login admin users in Yourls?

**Comment by IMIjrebassa** [comment]
don't worry I got it working

**Comment by mattv8** [comment]
Hey glad you got it working. What was the fix?

**Comment by IMIjrebassa** [comment]
Hello, finally the change that I made in plugin.php is not necessary, putting the corrects values for  alls the define( 'LDAPAUTH_xxxxx in config.php it works.

**Pull request closed without merging**
